import: globalconfig.txt
 
alert:
- slack
- hivealerter
 
description: This rule detects a DNS server error in which a specified plugin DLL
  (in registry) could not be loaded
filter:
- query:
    query_string:
      query: event_id:("150" "770")
index: logs-*
name: DNS-Server-Error-Failed-Loading-the-ServerLevelPluginDLL_0
priority: 1
realert:
  minutes: 0
type: any

alert_text:
	EventId: {0}\n
        Timestamp: {1}\n
        Index: {2}\n

alert_text_args: ["event_id", "@timestamp","_id"]
alert_text_type: alert_text_only

hive_alert_config:
	title: "{rule[name]}
	type: "external"
	source: "Elastalert"
	description: "This rule detects a DNS server error in which a specified plugin DLL (in registry) could not be loaded "
	severity: "1"
	tags: ["Security Alert", "Suspicious", "{match[event_id]}
	tlp: 1
	status: "New"
	follow: True

hive_observable_data_mapping:
  - index: "{match[_index]}"
  - timestamp: "{match[@timestamp]}"
  - event id: "{match[event_id]}"

