import: globalconfig.txt
 
alert:
- slack
- hivealerter
 
description: Detects the addition of a SSP to the registry. Upon a reboot or API call,
  SSP DLLs gain access to encrypted and plaintext passwords stored in Windows.
filter:
- query:
    query_string:
      query: ((event_id:"13" AND registry_key_path:("HKLM\\System\\CurrentControlSet\\Control\\Lsa\\Security\
        Packages" "HKLM\\System\\CurrentControlSet\\Control\\Lsa\\OSConfig\\Security\
        Packages")) AND NOT (process_path:"C\:\\Windows\\system32\\msiexec.exe" OR
        process_path:"C\:\\Windows\\syswow64\\MsiExec.exe"))
index: logs-endpoint-winevent-sysmon-*
name: Security-Support-Provider-SSP-added-to-LSA-configuration_0
priority: 1
realert:
  minutes: 0
type: any



alert_text:
	EventId: {0}\n
        Timestamp: {1}\n
        Index: {2}\n

alert_text_args: ["event_id", "@timestamp","_id"]
alert_text_type: alert_text_only

hive_alert_config:
	title: "{rule[name]}
	type: "external"
	source: "Elastalert"
	description: "Detects the addition of a SSP to the registry. Upon a reboot or API call,"
	severity: "1"
	tags: ["Security Alert", "Suspicious", "{match[event_id]}
	tlp: 1
	status: "New"
	follow: True

hive_observable_data_mapping:
  - index: "{match[_index]}"
  - timestamp: "{match[@timestamp]}"
  - event id: "{match[event_id]}"

